from turtle import *
def dreptunghi(culoare):
    color(culoare)
    pencolor('black')
    begin_fill()
    for i in range(2):
        forward(220)
        left(90)
        forward(270)
        left(90)
    end_fill()
def mutare_pozitie(poz1,dist):
    left(poz1)
    penup()
    forward(dist)    
def romb(culoare):
    color(culoare)
    begin_fill()
    pendown()
    left(80)
    forward(60)
    right(60)
    forward(60)
    right(120)
    forward(60)
    right(60)
    forward(60)
    end_fill()
def desenare_A(culoare):
    pendown()
    pencolor(culoare)
    right(15)
    forward(40)
    right(150)
    forward(40)
    right(180)
    forward(15)
    left(70)
    forward(10)
def romb_mic(culoare):
    pendown()
    pencolor('red')
    begin_fill()
    right(56)
    forward(20)
    right(60)
    forward(20)
    right(120)
    forward(20)
    right(60)
    forward(20)
    end_fill()

shape('turtle')
pensize(4)
pencolor('black')
speed(5)
bgcolor('green')
dreptunghi('white')
mutare_pozitie(40,140)
romb('red')
mutare_pozitie(300,101)
mutare_pozitie(270,140)
desenare_A('red')
mutare_pozitie(90, 30)
mutare_pozitie(90, 10)
romb_mic('red')
mutare_pozitie(300, 195)
mutare_pozitie(270,170)
desenare_A('red')
mutare_pozitie(90, 30)
mutare_pozitie(90, 5)
romb_mic('red')
hideturtle()
mainloop()
